# Generated by Django 4.0.3 on 2022-04-23 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('full_forms', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='full_form_data',
        ),
    ]
