# Generated by Django 4.0.3 on 2022-04-28 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('full_forms', '0005_full_form_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Full_Form_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='full_forms')),
                ('img_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='full_forms.full_form_data')),
            ],
        ),
    ]
