# Generated by Django 4.1 on 2022-09-06 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('full_forms', '0006_full_form_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Full_Form_Images',
        ),
    ]
