# Generated by Django 4.0.3 on 2022-05-03 05:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='web_stories_data',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
